development:
    debug: true
    database:
        driver: pdo_mysql
        host: localhost
        dbname: openstreetview
        user: root
        password:
        charset: utf8
    NBService: 
    MRService: 
    minify: false
testing:
    debug: false
    database:
        driver: pdo_mysql
        host: localhost
        dbname: 
        user: 
        password: 
        charset: utf8
    NBService:     
    MRService:     
    minify: true     
production:
    debug: false
    database:
        driver: pdo_mysql
        host: 
        dbname: 
        user: 
        password: 
        charset: utf8
    NBService: 
    MRService: 
    minify: true